<template>
  <div class="padded-element">
    <h2>What is CryptoWeddings?</h2>
    <p>
      CryptoWeddings is a Dapp (Decentralized Application) which uses the
      ethereum blockchain. It takes two addresses and creates a wedding smart
      contract (decentralized program on the ethereum blockchain). On this
      wedding smart contract, the two addresses can agree to marry (or not).
      This is set on the blockchain and cannot be changed by anyone other than
      the two parties who agreed to marry (divorces are possible). Spectators
      can watch live and send wedding gifts along with messages that will stay
      on the blockchain.
    </p>
    <h2>Why is this cool?</h2>
    <ul>
      <li>
        your wedding will live forever on the blockchain which is pretty neat :)
      </li>
      <li>
        couples who live in countries with governments that have rather
        opressive policies on non traditional relationships can marry on the
        blockchain and no one else can remove/delete it (the ethereum blockchain
        is immutable)
      </li>
    </ul>
    <h2>
      Does this mean anything in real life?
    </h2>
    <p>At the moment no. In the future? Who knows?</p>
    <h2>Who built this? Who helped?</h2>
    <p>
      The contracts and the decentralized application were created by
      <a href="https://codylamson.com" target="_blank">Cody Lamson</a>, code
      review and some minor changes to the smart contracts were performed by
      <a href="http://www.mattgstevens.com/" target="_blank">Matt Stevens</a>.
    </p>

    <p>
      My my wife,
      <a
        href="https://de.linkedin.com/in/alexandra-lamson-67526016a"
        target="_blank"
      >
        Alexandra Lamson
      </a>
      , was in charge of the wedding ceremony itself. CryptoWeddings was used
      during the ceremony. We had help from
      <a href="https://www.instagram.com/romylagodka/" target="_blank">
        Romy Lagodka
      </a>
      who worked on sound design and
      <a href="http://instagram.com/cayequitas" target="_blank">
        Carlos Serrano
      </a>
      who worked on the visual aspects of the wedding ceremony.
    </p>
    <h2>Interview on BlockTV</h2>
    <p>
      Enough interest was generated by the project and ceremony that we had an
      interview with BlockTV you can find it
      <a
        href="https://blocktv.com/watch/2019-07-18/5d307a2c6f719"
        target="_blank"
      >
        here
      </a>
      .
    </p>
    <h2>
      I want to have a wedding ceremony using CryptoWeddings. Can you help with
      that?
    </h2>
    <p>
      Sure, If you need technical assistance you should talk to Cody Lamson. If
      you need help/inspiration regarding the wedding ceremony, you should talk
      to Alexandra Lamson. Either way reach out to Cody and he will connect you
      with the right people. You can contact him
      <a href="https://codylamson.com/contact" target="_blank">here</a>.
    </p>
    <h2>Is the code for this project public?</h2>
    <p>Yes it is!</p>
    <p>
      <a
        href="https://github.com/TovarishFin/crypto-weddings-contracts"
        target="_blank"
      >
        CryptoWeddings smart contracts
      </a>
    </p>
    <p>
      <a
        href="https://github.com/TovarishFin/crypto-weddings-dapp-vue"
        target="_blank"
      >
        CryptoWeddings Decentralized Application
      </a>
    </p>
    <h2>I want to get in touch. How do I do that?</h2>
    <p>
      Feel free to reach out through any means listed on my
      <a href="https://codylamson.com/contact" target="_blank">
        personal site
      </a>
      .
    </p>
  </div>
</template>
